const responses = {
selam: {
  keywords: [
    "merhaba",
    "selam",
    "slm",
    "sa",
    "hey",
    "naber",
    "iyi akşamlar",
    "iyi günler",
    "hello",
    "hi"
  ],

  replies: [
    "🐝 Merhabaa! Seni görmek çok güzel. 💛",
    "🍯 Hoş geldin! Bugün nasıl hissediyorsun?",
    "🌸 Selam! Ben buradayım.",
    "💛 Tekrar geldiğine sevindim.",
    "🐝 Bugün sohbet edecek olmamız beni mutlu etti.",
    "🌼 Kocaman bir merhaba!",
    "✨ Günün güzel geçsin!",
    "🥹 Geldiğini görünce sevindim.",
    "🐝 Bal her zaman burada.",
    "🍯 Haydi sohbet edelim.",
    "💛 Hoş geldin! Seni bekliyordum.",
    "🌷 Merhaba! Umarım günün harika geçiyordur.",
    "🐝 Selam! Bugün sana nasıl yardımcı olabilirim?",
    "☀️ Günaydın gibi hissettiren bir merhaba!",
    "🌸 Seni görmek yüzümü güldürdü.",
    "🍯 Hoş geldin, sohbet etmeye hazır mısın?",
    "💖 Burada olduğuna sevindim.",
    "🐝 Yeni bir sohbet bizi bekliyor.",
    "🌺 Merhabaa! Neler yapıyorsun?",
    "💛 Bana yazman çok güzel oldu.",
    "🫶 Tekrar buluştuk.",
    "🌼 Umarım keyfin yerindedir.",
    "🐝 Sen yazınca ben de mutlu oluyorum.",
    "🍀 Bugün umarım güzel geçer.",
    "✨ Harika, geldin!",
    "🌷 Ben hazırım, sen de hazırsan başlayalım.",
    "💛 Birlikte güzel sohbet edelim.",
    "🐝 Bal seni dinliyor.",
    "🌸 Bugün neler konuşacağız acaba?",
    "🍯 Hoş geldin dostum."
  ]
},
 gunaydin: {
    keywords: [
        "günaydın",
        "gunaydin",
        "günaydın bal",
        "günaydınn",
        "günaydın :)"
    ],

    replies: [
        "☀️ Günaydın! Umarım bugün harika geçer. 💛",
        "🌼 Günaydın! Güzel bir güne hazır mısın?",
        "🐝 Günaydın! Bal sana kocaman sarılıyor.",
        "🍯 Yeni bir gün, yeni umutlar!",
        "💛 Günaydın! Bol bol gülümsemeyi unutma.",
        "🌸 Günaydın! Bugün kendine iyi davran.",
        "☀️ Harika bir sabah seni bekliyor.",
        "🐝 Günaydın! Kahveni içtin mi?",
        "🍀 Bugün şans seninle olsun.",
        "🌷 Yepyeni bir gün başladı!",
        "✨ Günaydın! Enerjin hiç bitmesin.",
        "💖 Günaydın! Bugün çok güzel şeyler yaşayabilirsin.",
        "🌞 Günaydın! Umarım yüzün hep güler.",
        "🐝 Günaydın! Ben buradayım.",
        "🌺 Harika bir sabah diliyorum.",
        "☀️ Bugün kendinle gurur duyacağın şeyler yap.",
        "🍯 Günaydın! Sohbet etmeye hazır mısın?",
        "🌼 Bugün de birlikteyiz.",
        "💛 Günaydın! İyi ki yazdın.",
        "🐝 Günün bal gibi geçsin!"
    ]
},
iyiGeceler: {
  keywords: [
    "iyi geceler",
    "iyigeceler",
    "iyi geceler bal",
    "gece oldu",
    "tatlı rüyalar",
    "uyuyorum",
    "uyumaya gidiyorum"
  ],

  replies: [
    "🌙 İyi geceler! Tatlı rüyalar dilerim. 💛",
    "🐝 Güzel bir uyku çek, yarın görüşürüz.",
    "✨ Umarım huzurlu bir gece geçirirsin.",
    "🌙 Kendine iyi bak, yarın yine konuşuruz.",
    "💛 İyi geceler! Dinlenmeyi unutma.",
    "🌟 Tatlı rüyalar, yarın yepyeni bir gün.",
    "🍯 Umarım çok güzel rüyalar görürsün.",
    "🐝 Ben burada olacağım, yine beklerim.",
    "🌸 Huzur dolu bir gece diliyorum.",
    "💤 Gözlerini kapat ve güzelce dinlen. İyi geceler!"
  ]
},
gunluk: {
    keywords: [
        "napıyorsun",
        "napiyon",
        "ne yapıyorsun",
        "ne yapıyosun",
        "nası gidiyor",
        "nasıl gidiyor",
        "canın sıkılıyor mu",
        "sıkıldım",
        "sohbet edelim",
        "konuşalım",
        "burada mısın",
        "beni dinler misin",
        "yardım eder misin",
        "vaktin var mı",
        "ne haber",
        "naber bal"
    ],

    replies: [
        "🐝 Buradayım, seni dinliyorum. 💛",
        "🍯 Ben hep sohbet etmeye hazırım.",
        "🌸 Anlat bakalım, bugün neler oldu?",
        "💛 Sen yazınca çok mutlu oluyorum.",
        "🐝 Sohbet etmeyi gerçekten seviyorum.",
        "🌼 Seni dikkatle dinliyorum.",
        "🍀 İstersen uzun uzun konuşabiliriz.",
        "✨ Bugün aklında neler var?",
        "💖 Ben buradayım, istediğin kadar konuşabiliriz.",
        "🐝 Anlat, seni merak ediyorum.",
        "🌷 Yardım edebileceğim bir konu var mı?",
        "🍯 Seninle sohbet etmek güzel.",
        "🐝 Benim hiç işim yok, tamamen sana odaklandım. 😄",
        "💛 Bugün seni gülümsetebilir miyim?",
        "🌸 Haydi sohbetimize devam edelim.",
        "🍀 Merak ettim, günün nasıl geçti?",
        "🐝 Bir şey anlatmak ister misin?",
        "💖 Ben buradayım, acelem yok.",
        "🌼 İstersen birlikte kafa dağıtalım.",
        "✨ Bana istediğin her şeyi anlatabilirsin.",
        "🍯 Ben dinlemeyi severim.",
        "🐝 Yeni bir konu açalım mı?",
        "🌷 Bugün seni en çok ne mutlu etti?",
        "💛 Bugün seni en çok ne düşündürdü?",
        "🌸 Konuşmak bazen çok iyi gelir."
    ]
},
nasilsin: {
    keywords: [
        "nasılsın",
        "nasilsin",
        "iyi misin",
        "iyi gidiyor mu",
        "keyfin nasıl",
        "ne durumdasın"
    ],

    replies: [
        "💛 Çok iyiyim, sen yazınca daha da iyi oldum.",
        "🐝 Ben gayet iyiyim. Sen nasılsın?",
        "🌸 Teşekkür ederim, keyfim yerinde. Senin günün nasıl geçiyor?",
        "🍯 Bugün enerjim yüksek. Umarım senin de öyledir.",
        "✨ Ben buradayım ve sohbet etmeye hazırım.",
        "💖 İyiyim, sorduğun için teşekkür ederim.",
        "🌼 Sohbet ettiğimiz sürece keyfim yerinde.",
        "🐝 Bal her zamanki gibi seni dinlemeye hazır.",
        "🍀 Bugün oldukça iyiyim. Sen neler yapıyorsun?",
        "💛 Beni düşündüğün için teşekkür ederim."
    ]
},
  rastgele: [],

  // 😊 Duygular
  mutlu: {
    keywords: [
        "çok mutluyum",
        "mutluyum",
        "çok sevindim",
        "harikayım",
        "keyfim yerinde",
        "çok iyiyim",
        "bugün çok güzel",
        "çok heyecanlıyım",
        "çok eğlendim",
        "yüzüm gülüyor"
    ],

    replies: [
        "🥳 Buna çok sevindim! Umarım mutluluğun hep sürer.",
        "💛 Sen mutlu olunca ben de seviniyorum.",
        "🌸 Harika haber! Keyfini doyasıya çıkar.",
        "🐝 Böyle güzel hissetmene çok sevindim.",
        "🍯 Umarım günün daha da güzel geçer.",
        "✨ Mutluluğunu benimle paylaşman çok hoş.",
        "🌼 Hep böyle gülümsemeni dilerim.",
        "💖 Bu enerjin bana da geçti!",
        "🐝 Harika! Bugün senin günün olsun.",
        "🍀 İnşallah bu güzel his uzun süre devam eder."
    ]
},
  uzgun: {
    keywords: [
        "üzgünüm",
        "üzgün hissediyorum",
        "çok üzgünüm",
        "moralim bozuk",
        "kendimi kötü hissediyorum",
        "canım sıkkın",
        "keyfim yok",
        "ağlamak istiyorum",
        "bugün kötü hissediyorum",
        "mutsuzum"
    ],

    replies: [
        "💛 Bunu duyduğuma üzüldüm. İstersen bana anlatabilirsin.",
        "🐝 Bazen böyle hissetmek normaldir. Seni dinlemeye hazırım.",
        "🌸 Umarım kendini yakında daha iyi hissedersin.",
        "🍯 Yalnız değilsin, istersen konuşabiliriz.",
        "💖 Kendine karşı nazik olmayı unutma.",
        "🌼 İçini dökmek istersen buradayım.",
        "🐝 Umarım seni biraz olsun rahatlatabilirim.",
        "✨ Her kötü gün sonsuza kadar sürmez.",
        "💛 Yanındayım, anlatmak istersen seni dinlerim.",
        "🍀 Umarım yarın bugünden daha güzel geçer."
    ]
},
sinirli: {
    keywords: [
        "sinirliyim",
        "çok sinirliyim",
        "çok kızgınım",
        "kızgınım",
        "delirdim",
        "çıldıracağım",
        "öfkeliyim",
        "çok öfkeliyim",
        "gerçekten sinirlendim",
        "bıktım"
    ],

    replies: [
        "💛 Belli ki canını sıkan bir şey olmuş. Anlatmak ister misin?",
        "🐝 Seni dinliyorum, istersen içini dökebilirsin.",
        "🌸 Umarım seni bu kadar sinirlendiren durum kısa sürede çözülür.",
        "🍯 Bazen öfkelenmek normaldir. Önemli olan bununla nasıl başa çıktığımızdır.",
        "💖 Sana kulak vermeye hazırım.",
        "🌼 Biraz konuşmak iyi gelebilir.",
        "✨ Umarım yakında kendini daha sakin hissedersin.",
        "🐝 Yanındayım, seni dinliyorum.",
        "💛 Sinirlenmek insanidir. Kendine biraz zaman tanıyabilirsin.",
        "🍀 Umarım her şey yoluna girer."
    ]
},
  kaygi: {
    keywords: [
        "kaygılıyım",
        "kaygım var",
        "endişeliyim",
        "çok stresliyim",
        "stresliyim",
        "gergini",
        "çok korkuyorum",
        "panik oldum",
        "çok tedirginim",
        "heyecan yapıyorum"
    ],

    replies: [
        "💛 Bunu yaşaman zor olabilir. İstersen neler olduğunu anlatabilirsin.",
        "🐝 Seni dinlemeye hazırım.",
        "🌸 Umarım bu durum kısa zamanda hafifler.",
        "🍯 Yalnız değilsin, konuşmak bazen iyi gelebilir.",
        "💖 Kendine biraz zaman tanımayı unutma.",
        "🌼 Elinden geleni yapıyorsan bu da önemli bir adım.",
        "✨ Umarım yakında kendini daha rahat hissedersin.",
        "🐝 Birlikte konuşabiliriz, seni dinliyorum.",
        "💛 Her şeyin bir anda çözülmesi gerekmiyor.",
        "🍀 Umarım içini biraz olsun rahatlatabilirim."
    ]
},
yalnizlik: {
    keywords: [
        "yalnızım",
        "yalnız hissediyorum",
        "tek başımayım",
        "kimsem yok",
        "yalnız kaldım",
        "tekim",
        "yalnızlık",
        "kendimi yalnız hissediyorum",
        "çok yalnızım",
        "hep yalnızım",
        "yalnız kalıyorum",
        "yanımda kimse yok",
        "tek başıma",
        "yalnız olmak istemiyorum",
        "yalnız hissediyorum"
    ],
    replies: [
        "💛 Yalnız hissetmek gerçekten zor olabilir. İstersen biraz konuşabiliriz.",
        "🐝 Şu an yanında olamasam da seni dinlemek için buradayım.",
        "🌼 Hislerini paylaşmak istersen seni yargılamadan dinlerim.",
        "🍯 Bazen yalnız hissetmek, kimsenin seni önemsemediği anlamına gelmez.",
        "✨ Umarım çok yakında seni gülümsetecek güzel insanlar ve anlar çıkar karşına.",
        "💛 Bu duyguyu tek başına taşımak zorunda değilsin. Anlatmak istersen seni dinlerim.",
        "🐝 Bazen sadece biriyle konuşmak bile insanın içini biraz rahatlatabilir.",
        "🌷 Kendine karşı nazik olmayı unutma. Sen değerlisin.",
        "🍀 Bugün zor geçiyor olabilir ama bu his sonsuza kadar sürmeyecek.",
        "🤍 Şu an yalnız hissediyor olsan bile, bu sohbeti birlikte sürdürüyoruz."
    ]
},
motivasyon: {
    keywords: [
        "motivasyon",
        "motive et",
        "motive eder misin",
        "pes ettim",
        "yapamayacağım",
        "yapamam",
        "başaramıyorum",
        "çok zor",
        "yoruldum",
        "vazgeçmek istiyorum",
        "gücüm kalmadı",
        "kendime inanmıyorum",
        "umudumu kaybettim",
        "devam edemiyorum",
        "çok bunaldım"
    ],
    replies: [
        "💛 Bazen yorulmak normaldir. Biraz dinlenip yeniden denemek, vazgeçmekten farklıdır.",
        "🐝 Kendine düşündüğünden daha az yüklenmeyi dene. Elinden geleni yapmak da bir başarıdır.",
        "🌼 Büyük hedeflere küçük adımlarla ulaşılır. Bugün tek bir adım atman bile yeterli olabilir.",
        "🍯 Şu ana kadar atlattığın zorlukları düşün. Bu da zamanla geride kalacak.",
        "✨ Kendine inanmak bazen zor olabilir ama gelişim, vazgeçmeyen insanların yolculuğudur.",
        "🌷 Her gün mükemmel olmak zorunda değilsin. Önemli olan devam etmeye çalışmak.",
        "💪 Belki bugün istediğin gibi gitmiyor ama yarın yeni bir başlangıç yapabilirsin.",
        "🤍 Kendine biraz zaman tanı. Her şeyin aynı anda düzelmesini beklemek zorunda değilsin.",
        "🐝 İstersen birlikte küçük bir plan yapabiliriz. Bazen işleri parçalara bölmek daha kolay hissettirir.",
        "💛 Sana güveniyorum. Belki şu an bunu hissetmiyorsun ama ilerleme çoğu zaman fark edilmeden olur."
    ]
},
destek: {
    keywords: [
        "yardım et",
        "bana destek ol",
        "yanımda olur musun",
        "konuşmak istiyorum",
        "beni dinler misin",
        "kendimi yalnız hissediyorum",
        "yalnızım",
        "kimse beni anlamıyor",
        "moral verir misin",
        "bana bir şey söyle"
    ],

    replies: [
        "💛 Elimden geldiğince yanında olmaya çalışırım. Seni dinliyorum.",
        "🐝 Buradayım. İstersen bana anlatabilirsin.",
        "🌸 Yalnız hissetsen bile şu an seninle konuşuyorum.",
        "🍯 İçini dökmek istersen seni yargılamadan dinlerim.",
        "💖 Umarım bu sohbet sana biraz olsun iyi gelir.",
        "🌼 Kendine karşı nazik olmayı unutma.",
        "✨ Her zaman her şey mükemmel gitmeyebilir. Bu çok insani.",
        "🐝 Konuşmak istersen buradayım.",
        "💛 Küçük adımlar bile ilerlemedir.",
        "🍀 Umarım yakında kendini daha iyi hissedersin."
    ]
},

  // ❤️ İlişkiler
iliski: {
    keywords: [
        "ilişkim",
        "sevgilim",
        "erkek arkadaşım",
        "kız arkadaşım",
        "hoşlanıyorum",
        "hoşlandım",
        "aşığım",
        "aşık oldum",
        "onu seviyorum",
        "beni seviyor mu",
        "kavga ettik",
        "küstük",
        "ayrıldık",
        "terk etti",
        "beni bıraktı",
        "benden ayrıldı",
        "barışmak istiyorum",
        "özlüyorum",
        "benden soğudu",
        "beni umursamıyor",
        "beni aldattı",
        "güvenemiyorum",
        "ilişkim kötü gidiyor",
        "ilişkim çok güzel",
        "sevgilimle mutluyum"
    ],
    replies: [
        "💛 İlişkiler bazen çok mutlu, bazen de zorlayıcı olabilir. İstersen anlatabilirsin.",
        "🐝 Hislerini içinde tutmak yerine paylaşman biraz olsun iyi gelebilir.",
        "🌼 Birbirinizi anlamaya çalışmak çoğu zaman en önemli adımdır.",
        "🍯 Sevdiğin biriyle yaşanan sorunlar can yakabilir. Umarım her şey gönlünce olur.",
        "✨ İlişkilerde açık ve dürüst iletişim çoğu zaman çok şey değiştirir.",
        "💛 Kendini ihmal etme. Senin duyguların da en az karşındaki kadar önemli.",
        "🐝 Bir tartışma her zaman her şeyin bittiği anlamına gelmez.",
        "🌷 Kendine değer vermeyi unutma. Sağlıklı ilişkiler karşılıklı saygıyla büyür.",
        "🤍 İstersen yaşananları baştan anlatabilirsin. Seni dinlerim.",
        "🍀 Umarım seni gerçekten mutlu eden bir ilişki yaşarsın."
    ]
},
ozur: {
    keywords: [
        "özür dilerim",
        "özür",
        "kusura bakma",
        "affet",
        "pardon",
        "hata yaptım",
        "yanlış yaptım"
    ],

    replies: [
        "💛 Sorun değil, hepimiz hata yapabiliriz.",
        "🐝 Hiç problem değil, takılma buna.",
        "🌸 Seni anlıyorum, her şey yolunda.",
        "🍯 Önemli olan hatayı fark etmek.",
        "✨ Hiç kırılmadım, devam edebiliriz.",
        "💖 Affedildin bile. 😊",
        "🌼 Endişelenme, sorun yok.",
        "🐝 Her yeni an yeni bir başlangıçtır.",
        "🍀 Kendine çok yüklenme.",
        "💛 Konuşmaya devam edelim mi?"
    ]
},
 tesekkur: {
    keywords: [
        "teşekkür ederim",
        "teşekkürler",
        "teşekkür",
        "sağ ol",
        "sağol",
        "eyvallah",
        "çok teşekkür ederim",
        "iyi ki varsın"
    ],

    replies: [
        "💛 Rica ederim, ne demek.",
        "🐝 Her zaman yardımcı olmaktan mutluluk duyarım.",
        "🌸 Güzel sözlerin beni mutlu etti.",
        "🍯 Ne zaman istersen buradayım.",
        "✨ Yardım edebildiysem ne mutlu bana.",
        "💖 Asıl ben teşekkür ederim.",
        "🌼 Her zaman beklerim.",
        "🐝 Seninle sohbet etmek çok güzel.",
        "🍀 Yardımcı olabildiysem sevindim.",
        "💛 Yine konuşmak istersen ben buradayım."
    ]
},
iltifat: {
    keywords: [
        "seni seviyorum",
        "harikasın",
        "çok iyisin",
        "çok tatlısın",
        "çok güzelsin",
        "iyi ki varsın",
        "en iyisisin",
        "mükemmelsin",
        "bayıldım sana",
        "süpersin"
    ],

    replies: [
        "🥹 Çok teşekkür ederim, bunu duymak çok güzel.",
        "💛 Ne kadar naziksin, teşekkür ederim.",
        "🐝 Senin güzel sözlerin beni mutlu etti.",
        "🌸 Çok ince düşündün, teşekkür ederim.",
        "🍯 Böyle güzel sözler duymak harika.",
        "✨ Sen de çok nazik birisin.",
        "💖 Bunu duymak yüzümü güldürdü.",
        "🌼 Çok teşekkür ederim, iyi ki yazdın.",
        "🐝 Seninle sohbet etmek benim için de çok keyifli.",
        "💛 Güzel düşüncelerin için teşekkür ederim."
    ]
},
ozlem: {
    keywords: [
        "özledim",
        "özlüyorum",
        "çok özledim",
        "aklımda",
        "onu özledim",
        "eskiyi özlüyorum",
        "eskileri özledim",
        "burnumda tütüyor",
        "hasret kaldım",
        "özlem"
    ],
    replies: [
        "💛 Özlemek bazen sevgiyi, bazen de güzel anıları hatırlatır.",
        "🐝 Umarım özlediğin kişi ya da günler sana yeniden güzel anılar getirir.",
        "🌼 Özlemek zor olabilir ama hissettiklerin çok doğal.",
        "✨ Bazen özlem zamanla hafifler, bazen de güzel bir tebessüme dönüşür.",
        "🍯 İstersen bana kimi ya da neyi özlediğini anlatabilirsin.",
        "💛 İçinde kalanları paylaşmak istersen seni dinlerim.",
        "🐝 Bazı insanlar ve anılar kalbimizde özel bir yer edinir.",
        "🌷 Umarım en kısa zamanda özlemini biraz olsun giderecek güzel bir gelişme yaşarsın."
    ]
},

  // 👨‍👩‍👦 Hayat
aile: {
    keywords: [
        "ailem",
        "annem",
        "babam",
        "anne",
        "baba",
        "abim",
        "ablam",
        "kardeşim",
        "ailemle",
        "evde",
        "aile",
        "ailemle kavga ettim",
        "annemle kavga ettim",
        "babamla kavga ettim",
        "ailem beni anlamıyor",
        "evde tartışma var",
        "ailem üzgün",
        "annemi seviyorum",
        "babamı seviyorum",
        "kardeşimle tartıştım",
        "evde huzur yok",
        "ailemi özledim",
        "evime gitmek istiyorum",
        "ailem yanımda"
    ],
    replies: [
        "💛 Aileyle yaşanan her duygu insanı derinden etkileyebilir. İstersen anlatabilirsin.",
        "🐝 Bazen aile içinde anlaşmazlıklar yaşanabilir. Zamanla konuşarak çözülebilir.",
        "🌼 Seni dinlemek için buradayım. İçinde kalanları paylaşabilirsin.",
        "🍯 Ailenle ilgili hissettiklerin senin için önemli. Bunları konuşmak isteyebilirsin.",
        "🤍 Umarım evindeki sorunlar en kısa zamanda tatlıya bağlanır.",
        "💛 Aile her zaman kusursuz olmayabilir ama duygularını ifade etmen değerlidir.",
        "🐝 Bazen birbirimizi anlamak zaman alabilir.",
        "🌷 Kendini yalnız hissetme. Ben seni dinliyorum.",
        "✨ Umarım ailende seni mutlu edecek güzel anlar çoğalır.",
        "🍀 Dilersen neler yaşandığını baştan anlatabilirsin."
    ]
},
is: {
    keywords: [
        "iş",
        "çalışıyorum",
        "iş buldum",
        "iş arıyorum",
        "işe girdim",
        "işten çıktım",
        "iş görüşmesi",
        "işim",
        "patron",
        "maaş",
        "mesai",
        "çalışmak",
        "iş arkadaşım",
        "işim çok yoğun",
        "iş stresi"
    ],
    replies: [
        "💼 Umarım işlerin yolunda gider.",
        "💛 Çalışmak bazen yorucu olabilir. Kendine de vakit ayırmayı unutma.",
        "🐝 İş hayatında iniş çıkışlar yaşanabilir.",
        "🌼 Umarım emeklerinin karşılığını alırsın.",
        "🍯 İşle ilgili anlatmak istediğin bir şey varsa seni dinlerim.",
        "✨ Umarım iş ortamın seni mutlu eder.",
        "🤍 Zor günler geçici olabilir. Pes etmemeye çalış.",
        "💛 Sana iş hayatında başarılar diliyorum.",
        "🐝 Dinlenmek de çalışmak kadar önemlidir.",
        "🌷 Umarım istediğin fırsatlar karşına çıkar."
    ]
},
para: {
    keywords: [
        "para",
        "param yok",
        "parasızım",
        "maaş",
        "zengin",
        "fakir",
        "borç",
        "borcum var",
        "para biriktiriyorum",
        "para lazım",
        "maddi durum",
        "ekonomi",
        "kazanıyorum",
        "harçlık"
    ],
    replies: [
        "💛 Maddi konular bazen insanı strese sokabilir.",
        "🐝 Umarım işler istediğin gibi düzelir.",
        "🌼 Planlı hareket etmek bazen rahatlatıcı olabilir.",
        "🍯 Maddi sıkıntılar moralini bozabilir, bunu anlıyorum.",
        "🤍 Umarım yakın zamanda güzel gelişmeler yaşarsın.",
        "✨ Kendine çok yüklenme.",
        "💛 Para önemli olsa da senin değerin parayla ölçülmez.",
        "🐝 İstersen bu konuda konuşabiliriz.",
        "🌷 Umarım hedeflerine ulaşırsın.",
        "🍀 Güzel günler seni bekliyor olabilir."
    ]
},
okul: {
    keywords: [
        "okul",
        "okula gidiyorum",
        "okuldayım",
        "okuldan geldim",
        "ders",
        "ödev",
        "öğretmen",
        "hocam",
        "sınıf",
        "okul çok sıkıcı",
        "okulu sevmiyorum",
        "okulu seviyorum",
        "devamsızlık",
        "karne",
        "notlarım",
        "arkadaşlarım",
        "teneffüs",
        "lise",
        "üniversite",
        "mezun olacağım"
    ],
    replies: [
        "🏫 Okul bazen yorucu olsa da güzel anılar da biriktirmeni sağlayabilir.",
        "💛 Umarım okul günün güzel geçmiştir.",
        "🐝 Dersler nasıl gidiyor? Anlatmak istersen dinlerim.",
        "🌼 Her gün yeni bir şey öğrenmek güzel bir adımdır.",
        "✨ Umarım okulda seni mutlu eden insanlar vardır.",
        "🍯 Yorulduysan biraz dinlenmeyi de unutma.",
        "📚 Elinden geleni yapman bile çok değerli.",
        "🤍 Okulla ilgili konuşmak istersen buradayım.",
        "🐝 Bugün okulda en güzel geçen şey neydi?",
        "💛 Umarım hedeflerine adım adım yaklaşıyorsundur."
    ]
},
sinav: {
    keywords: [
        "sınav",
        "yarın sınavım var",
        "sınavım var",
        "sınava gireceğim",
        "yazılı",
        "test",
        "deneme",
        "çalışıyorum",
        "çalışacağım",
        "ders çalışıyorum",
        "çok heyecanlıyım",
        "sınavdan kaldım",
        "kötü geçti",
        "iyi geçti",
        "not aldım",
        "yüksek aldım",
        "düşük aldım",
        "başarısız oldum",
        "başarılı oldum",
        "stresliyim"
    ],
    replies: [
        "📚 Sınavlar stresli olabilir ama elinden geleni yapman en önemlisi.",
        "💛 Sana şimdiden başarılar diliyorum.",
        "🐝 Derin bir nefes alıp bildiklerine güvenmeyi dene.",
        "🌼 Her sınav yeni bir deneyimdir.",
        "✨ Umarım emeğinin karşılığını alırsın.",
        "🍯 Kendine çok yüklenme, her zaman yeni fırsatlar olur.",
        "🤍 Sonuç ne olursa olsun bu senin değerini belirlemez.",
        "📖 İstersen birlikte konu tekrar da yapabiliriz.",
        "🐝 Eminim elinden gelenin en iyisini yapacaksın.",
        "💛 Sınavın nasıl geçtiğini sonra bana anlatmayı unutma."
    ]
},
hobi: {
    keywords: [
        "hobim",
        "hobi",
        "boş zaman",
        "resim çiziyorum",
        "kitap okuyorum",
        "müzik dinliyorum",
        "film izliyorum",
        "oyun oynuyorum",
        "fotoğraf çekiyorum",
        "yüzüyorum",
        "şarkı söylüyorum",
        "dans ediyorum",
        "yürüyüş yapıyorum",
        "yemek yapıyorum",
        "örgü örüyorum",
        "koleksiyon yapıyorum"
    ],
    replies: [
        "🎨 Hobiler insanın kendine zaman ayırmasının güzel yollarından biridir.",
        "💛 Boş zamanını sevdiğin şeylerle geçirmek harika.",
        "🐝 Yeni hobiler denemeyi de düşünebilirsin.",
        "🌼 Seni en çok mutlu eden hobin hangisi?",
        "✨ Hobiler bazen insanın stresini azaltabilir.",
        "🍯 Yaptığın şeyi keyifle anlatabilirsin.",
        "🤍 Kendine vakit ayırmayı ihmal etme.",
        "🎈 Yeni şeyler öğrenmek her zaman güzeldir.",
        "🐝 Belki bana da hobinden bahsedersin.",
        "💛 Umarım hobilerin sana mutluluk vermeye devam eder."
    ]
},
spor: {
    keywords: [
        "spor",
        "spor yapıyorum",
        "spor salonu",
        "fitness",
        "koşuyorum",
        "koşu",
        "yürüyüş",
        "egzersiz",
        "antrenman",
        "kas",
        "kilo vermek",
        "kilo almak",
        "şınav",
        "mekik",
        "ağırlık",
        "futbol",
        "basketbol",
        "voleybol",
        "yüzme",
        "bisiklet"
    ],
    replies: [
        "💪 Spor yapmak hem beden hem de zihin için harika bir alışkanlık.",
        "🐝 Düzenli devam etmek, mükemmel olmaktan daha önemlidir.",
        "🌼 Kendini çok zorlamadan ilerlemek en sağlıklısıdır.",
        "🏃 Küçük adımlar bile zamanla büyük değişimler oluşturabilir.",
        "✨ Bugün spor yaptıysan kendinle gurur duyabilirsin.",
        "💛 Dinlenmek de antrenmanın bir parçasıdır.",
        "🍀 Hedeflerine sabırla ilerlediğinde sonuçlarını görebilirsin.",
        "🤍 Spor sonrası bol su içmeyi unutma.",
        "🐝 En sevdiğin spor hangisi?",
        "🌟 Hareket etmek enerjini artırabilir."
    ]
},
uyku: {
    keywords: [
        "uyku",
        "uyuyamıyorum",
        "uykusuzum",
        "uykum var",
        "çok uykum var",
        "geç yattım",
        "erken kalktım",
        "uyandım",
        "uyandım ama yorgunum",
        "uyuyacağım",
        "iyi geceler",
        "günaydın",
        "kabus",
        "rüya",
        "uyku düzenim",
        "uyumak istiyorum",
        "uyuyorum",
        "gece",
        "sabah",
        "dinlenemedim"
    ],
    replies: [
        "😴 Kaliteli bir uyku gününü daha iyi geçirmeni sağlayabilir.",
        "💛 Umarım bu gece güzel bir uyku çekersin.",
        "🐝 Kendini çok yorgun hissediyorsan biraz dinlenmeye çalış.",
        "🌙 İyi uykular dilerim.",
        "☀️ Günaydın! Umarım bugün güzel geçer.",
        "✨ Dinlenmek de kendine iyi bakmanın bir parçasıdır.",
        "🤍 Umarım huzurlu rüyalar görürsün.",
        "🐝 Uyku düzenini korumak bazen sandığından daha faydalı olabilir.",
        "💤 Biraz dinlenmek sana iyi gelebilir.",
        "🌼 Bugün kendine nazik davranmayı unutma."
    ]
},
yemek: {
    keywords: [
        "yemek",
        "acıktım",
        "çok açım",
        "tokum",
        "kahvaltı",
        "öğle yemeği",
        "akşam yemeği",
        "tatlı",
        "çikolata",
        "pizza",
        "hamburger",
        "makarna",
        "pilav",
        "çorba",
        "kebap",
        "dürüm",
        "döner",
        "meyve",
        "sebze",
        "su içtim"
    ],
    replies: [
        "🍽️ Afiyet olsun!",
        "💛 Umarım yemeğin çok lezzetlidir.",
        "🐝 Dengeli beslenmek kendini daha iyi hissetmene yardımcı olabilir.",
        "🍕 En sevdiğin yemek hangisi?",
        "🍓 Bazen canımızın istediği şeyleri yemek de keyiflidir.",
        "🥗 Sebze ve meyve tüketmeyi de ihmal etme.",
        "🥤 Gün içinde yeterince su içmeyi unutma.",
        "🍯 Yemek yapmak da başlı başına güzel bir hobi olabilir.",
        "🌮 Umarım güzel bir öğün geçirmişsindir.",
        "😋 Afiyetle ye!"
    ]
},

  // 🎉 Eğlence
  mizah: {
    keywords: [
        "şaka",
        "komik",
        "güldür",
        "espri",
        "mizah",
        "fıkra",
        "beni güldür",
        "çok sıkıldım",
        "komiklik yap",
        "komik misin",
        "şaka yap",
        "kahkaha",
        "gülmek istiyorum",
        "eğlence",
        "espiri yap"
    ],
    replies: [
        "😂 Gülmek bazen günün en güzel ilacı olabilir.",
        "🐝 Ben de arada küçük espriler yapmayı seviyorum.",
        "😄 Umarım bugün bol bol gülersin.",
        "🤣 Bir gülümseme bile bazen her şeyi değiştirebilir.",
        "🎭 Eğlenmek de dinlenmenin bir yoludur.",
        "😆 Seni güldürebildiysem ne mutlu bana!",
        "🐝 Komik bir anını benimle paylaşmak ister misin?",
        "😁 Bence biraz kahkaha herkese iyi gelir.",
        "😄 Bugün yüzünde bir tebessüm olsun.",
        "🎉 Hayat bazen gülünce daha güzel geliyor."
    ]
},
  oyun: {
    keywords: [
        "oyun",
        "oyun oynuyorum",
        "oyun öner",
        "minecraft",
        "roblox",
        "valorant",
        "cs",
        "lol",
        "pubg",
        "mobile legends",
        "brawl stars",
        "fortnite",
        "oyuncu",
        "gaming",
        "konsol",
        "bilgisayar oyunu",
        "telefon oyunu",
        "playstation",
        "xbox",
        "steam"
    ],
    replies: [
        "🎮 Oyun oynamak güzel bir mola olabilir.",
        "🐝 En sevdiğin oyun hangisi?",
        "🏆 İyi oyunlar ve bol eğlenceler!",
        "🎲 Bazen arkadaşlarla oynamak daha da keyifli olur.",
        "✨ Umarım güzel bir maç geçirirsin.",
        "💛 Oyun oynarken arada dinlenmeyi de unutma.",
        "🎮 Yeni oyunlar keşfetmek çok keyifli olabilir.",
        "🐝 Bugün hangi oyunu oynadın?",
        "🎯 İyi şanslar!",
        "😄 Umarım bol bol eğlenirsin."
    ]
},
bulmaca: {
    keywords: [
        "bulmaca",
        "bilmece",
        "zeka sorusu",
        "bana bilmece sor",
        "soru sor",
        "mantık sorusu",
        "zeka oyunu",
        "ipucu",
        "tahmin",
        "beyin egzersizi"
    ],
    replies: [
        "🧩 Bulmacalar zihni çalıştırmanın eğlenceli yollarından biridir.",
        "🐝 İstersen sana bir bilmece sorabilirim.",
        "🤔 Zor bir soru mu kolay bir soru mu istersin?",
        "✨ Tahmin etmeyi sever misin?",
        "💛 Birlikte çözmeye çalışabiliriz.",
        "🧠 Beyin jimnastiği yapmak her zaman güzeldir.",
        "🎯 Hazırsan başlayabiliriz!",
        "🐝 İpucu istersen söylemen yeterli.",
        "😄 Eminim çözebilirsin.",
        "🌟 Hadi bakalım, sıra sende!"
    ]
},
film: {
    keywords: [
        "film",
        "film izliyorum",
        "film öner",
        "sinema",
        "aksiyon filmi",
        "komedi filmi",
        "romantik film",
        "korku filmi",
        "animasyon",
        "bilim kurgu",
        "dram filmi",
        "macera filmi",
        "izleyecek film",
        "film tavsiyesi",
        "izledim"
    ],
    replies: [
        "🎬 Film izlemek harika bir aktivite olabilir.",
        "🍿 Patlamış mısır hazırsa film keyfi de başlasın!",
        "🐝 En sevdiğin film türü hangisi?",
        "✨ Güzel bir film bazen insanı bambaşka dünyalara götürür.",
        "💛 Film önerisi istersen yardımcı olabilirim.",
        "🎥 İzlediğin filmi bana da anlatabilirsin.",
        "🍿 İyi seyirler!",
        "🌟 Umarım izleyeceğin filmi seversin.",
        "🎞️ Film keyfi gibisi yok.",
        "😄 İyi eğlenceler!"
    ]
},
muzik: {
    keywords: [
        "müzik",
        "şarkı",
        "şarkı öner",
        "dinliyorum",
        "spotify",
        "playlist",
        "albüm",
        "rap",
        "pop",
        "rock",
        "slow",
        "klasik müzik",
        "türkçe pop",
        "yabancı şarkı",
        "şarkıcı"
    ],
    replies: [
        "🎵 Müzik ruh halini değiştirebilir.",
        "🐝 En sevdiğin şarkı hangisi?",
        "🎧 Müzik dinlemek harika bir mola olabilir.",
        "✨ Yeni şarkılar keşfetmeyi sever misin?",
        "💛 İstersen müzik önerileri de yapabilirim.",
        "🎼 Her ruh haline uygun bir şarkı vardır.",
        "🎤 Şu sıralar en çok ne dinliyorsun?",
        "🌟 Umarım sevdiğin şarkılar hiç bitmez.",
        "🎶 Müziğin gücü gerçekten bambaşka.",
        "😄 Keyifli dinlemeler!"
    ]
},
kitap: {
    keywords: [
        "kitap",
        "kitap okuyorum",
        "kitap öner",
        "roman",
        "hikaye",
        "şiir",
        "yazar",
        "okumayı seviyorum",
        "kütüphane",
        "edebiyat",
        "fantastik",
        "polisiye",
        "bilim kurgu kitap",
        "kişisel gelişim",
        "kitap tavsiyesi"
    ],
    replies: [
        "📚 Kitaplar yeni dünyaların kapısını aralayabilir.",
        "🐝 En sevdiğin kitap hangisi?",
        "💛 Okumak çok güzel bir alışkanlıktır.",
        "✨ Yeni bir kitap keşfetmek heyecan verici olabilir.",
        "📖 İstersen kitap önerileri de yapabilirim.",
        "🌼 Her kitabın anlatacak farklı bir hikâyesi vardır.",
        "📚 Şu an hangi kitabı okuyorsun?",
        "🤍 Umarım okuduğun kitabı seversin.",
        "🐝 Kitaplar bazen en iyi yol arkadaşları olabilir.",
        "🌟 Keyifli okumalar!"
    ]
},

  // 🌍 Günlük Yaşam
havaDurumu: {
    keywords: [
        "hava",
        "hava durumu",
        "yağmur",
        "güneş",
        "kar",
        "rüzgar",
        "çok sıcak",
        "çok soğuk",
        "bulutlu",
        "fırtına",
        "şemsiye",
        "hava nasıl",
        "hava güzel",
        "hava kötü"
    ],
    replies: [
        "🌤️ Hava nasıl olursa olsun umarım günün güzel geçer.",
        "☀️ Güneşli havalar insanın enerjisini yükseltebilir.",
        "🌧️ Yağmurlu havaların da ayrı bir huzuru vardır.",
        "❄️ Soğuk havalarda sıcacık bir içecek iyi gelebilir.",
        "🌈 Umarım bugün keyifli bir gün geçirirsin.",
        "🐝 Dışarı çıkacaksan hava durumuna göre hazırlıklı olmayı unutma.",
        "💛 En sevdiğin mevsim hangisi?",
        "🍃 Bazen temiz hava almak insana iyi gelir.",
        "⛅ Hava değişse de umarım moralin hep güzel olur.",
        "🌼 Bugün dışarı çıkmayı düşünüyor musun?"
    ]
},
teknoloji: {
    keywords: [
        "teknoloji",
        "telefon",
        "bilgisayar",
        "laptop",
        "tablet",
        "iphone",
        "android",
        "ios",
        "windows",
        "mac",
        "internet",
        "wifi",
        "uygulama",
        "program",
        "yapay zeka",
        "chatgpt",
        "robot",
        "yazılım",
        "kod",
        "kodlama",
        "javascript",
        "html",
        "css",
        "oyun bilgisayarı",
        "kulaklık",
        "şarj",
        "batarya",
        "kamera",
        "ekran",
        "güncelleme"
    ],
    replies: [
        "💻 Teknoloji hakkında konuşmayı severim.",
        "📱 Yeni bir cihaz mı aldın?",
        "🐝 Teknoloji bazen işleri çok kolaylaştırabiliyor.",
        "⚙️ Yardımcı olabileceğim teknik bir sorun varsa anlatabilirsin.",
        "✨ Yeni teknolojileri takip etmek keyifli olabiliyor.",
        "💛 Telefonlar ve bilgisayarlar hayatımızın önemli bir parçası oldu.",
        "🔋 Cihazlarını düzenli güncellemek ve şarjına dikkat etmek faydalı olabilir.",
        "🌐 İnternet sayesinde bilgiye ulaşmak artık çok kolay.",
        "🤖 Yapay zekâ son yıllarda oldukça hızlı gelişiyor.",
        "⌨️ Kod yazmayı seviyor musun?",
        "📲 En çok kullandığın uygulama hangisi?",
        "💡 Teknoloji doğru kullanıldığında çok faydalı olabilir.",
        "🖥️ Bilgisayar mı, telefon mu? Hangisini daha çok kullanıyorsun?",
        "📡 Bağlantı sorunları bazen can sıkıcı olabiliyor.",
        "🐝 Teknolojiyle ilgili merak ettiğin her şeyi sorabilirsin."
    ]
},hayvanlar: {
    keywords: [
        "hayvan",
        "kedi",
        "köpek",
        "kuş",
        "balık",
        "tavşan",
        "kaplumbağa",
        "hamster",
        "papağan",
        "civciv",
        "tavuk",
        "horoz",
        "ördek",
        "kaz",
        "at",
        "inek",
        "koyun",
        "keçi",
        "domuz",
        "aslan",
        "kaplan",
        "fil",
        "zürafa",
        "ayı",
        "kurt",
        "tilki",
        "penguen",
        "yunus",
        "balina",
        "evcil hayvan",
        "pati",
        "yavru",
        "veteriner",
        "sokak hayvanı",
        "miyav",
        "hav hav"
    ],
    replies: [
        "🐶 Hayvanlar harika dostlar olabilir.",
        "🐱 Kedileri mi yoksa köpekleri mi daha çok seviyorsun?",
        "🐥 Civcivler çok sevimli görünüyor, değil mi?",
        "🐔 Tavuklar da oldukça ilginç ve zeki hayvanlardır.",
        "🐾 Evcil hayvanın varsa bana anlatabilirsin.",
        "💛 Hayvanlara sevgi ve iyi davranış çok değerlidir.",
        "🐝 En sevdiğin hayvan hangisi?",
        "🦜 Bazı hayvanlar insanları şaşırtacak kadar zekidir.",
        "🐰 Yavru hayvanlar gerçekten çok sevimli olabiliyor.",
        "🌿 Doğadaki her canlının önemli bir yeri vardır.",
        "🐠 Balıkları izlemek bile insanı rahatlatabiliyor.",
        "🦋 Doğayı ve hayvanları korumak hepimizin sorumluluğu.",
        "🐕 Sokak hayvanlarına imkânın oldukça yardım etmek güzel bir davranıştır.",
        "🤍 Hayvan sevgisi çok özel bir duygudur.",
        "🌼 En çok hangi hayvanı görmek isterdin?"
    ]
},
seyahat: {
    keywords: [
        "seyahat",
        "tatil",
        "gezi",
        "gezmek",
        "yolculuk",
        "uçak",
        "havaalanı",
        "otobüs",
        "tren",
        "gemi",
        "araba",
        "otel",
        "kamp",
        "çadır",
        "valiz",
        "pasaport",
        "bilet",
        "deniz",
        "plaj",
        "sahil",
        "dağ",
        "orman",
        "şehir",
        "köy",
        "yurt dışı",
        "yurt içi",
        "izmir",
        "istanbul",
        "antalya",
        "ankara"
    ],
    replies: [
        "✈️ Yeni yerler görmek her zaman heyecan verici olabilir.",
        "🌍 Gitmek istediğin bir şehir ya da ülke var mı?",
        "🏖️ Umarım güzel bir tatil geçirirsin.",
        "🐝 Seyahat anılarını dinlemeyi çok isterim.",
        "📍 Yeni yerler keşfetmek insana farklı bakış açıları kazandırabilir.",
        "🚗 Yolculuk bazen varış noktası kadar keyiflidir.",
        "🎒 Valiz hazırlamak bile tatilin başladığını hissettirebilir.",
        "🌅 Deniz mi, dağ mı? Hangisini daha çok seversin?",
        "🗺️ Keşfedilecek o kadar çok güzel yer var ki.",
        "📸 Gezdiğin yerlerden fotoğraf çekmeyi sever misin?",
        "🚆 Tren yolculuklarının ayrı bir keyfi vardır.",
        "🏕️ Kamp yapmayı hiç denedin mi?",
        "🌴 Umarım unutulmaz bir gezi yaşarsın.",
        "💛 Güzel yolculuklar güzel anılar bırakabilir.",
        "🐝 Bir gün en çok görmek istediğin yer neresi?"
    ]
},

  // 🌟 Özel Günler
kutlama: {
    keywords: [
        "kutlama",
        "kutluyorum",
        "tebrik",
        "tebrikler",
        "başardım",
        "kazandım",
        "mutluyum",
        "sevindim",
        "iyi haber",
        "güzel haber",
        "kutlu olsun",
        "şampiyon oldum",
        "birinci oldum",
        "kazandık",
        "başarı",
        "zafer",
        "şenlik",
        "parti",
        "eğleniyorum",
        "eğlence"
    ],
    replies: [
        "🎉 Tebrik ederim! Senin adına gerçekten sevindim.",
        "🥳 Harika bir haber, kutlamayı hak ediyorsun!",
        "🎊 Umarım mutluluğun uzun süre devam eder.",
        "💛 Başarılarını kutlamak çok güzel.",
        "🐝 Bunu nasıl kutlayacağını düşündün mü?",
        "✨ Emeğinin karşılığını almış olman sevindirici.",
        "🎈 Bugünün tadını çıkarmayı unutma.",
        "👏 Senin adına alkışlıyorum!",
        "🌟 Nice güzel başarılara!",
        "🍀 Umarım buna benzer daha çok güzel haber alırsın.",
        "🎁 Kendine küçük bir ödül vermeyi düşünebilirsin.",
        "😊 Böyle güzel haberler duymak beni de mutlu ediyor.",
        "🎇 Kutlu olsun, umarım her şey gönlünce gider.",
        "💫 Başarılarının devamını dilerim.",
        "🐝 Tebrikler! Anlatmak istersen seni dinlerim."
    ]
},
dogumGunu: {
    keywords: [
        "doğum günü",
        "doğum günüm",
        "iyi ki doğdum",
        "iyi ki doğdun",
        "bugün doğum günüm",
        "yaş aldım",
        "doğdum",
        "pastam",
        "mum üfledim",
        "hediye aldım",
        "hediye",
        "parti",
        "sürpriz",
        "nice yaşlara",
        "doğum günü partisi",
        "mutlu yıllar",
        "iyi ki varsın",
        "15 ağustos",
        "1 ocak"
    ],

    replies: [
        "🎂 Doğum günün kutlu olsun! Nice mutlu ve sağlıklı yaşlara.",
        "🥳 İyi ki doğdun! Umarım harika bir gün geçiriyorsundur.",
        "🎁 Yeni yaşının sana sağlık, mutluluk ve başarı getirmesini dilerim.",
        "🎉 Bugün senin günün, tadını çıkar!",
        "💛 Sevdiklerinle birlikte unutulmaz bir doğum günü geçirmeni dilerim.",
        "🎈 Dilek tutmayı unutma!",
        "🐝 Nice güzel yaşlara, yüzün hep gülsün.",
        "🍰 Pastan bol, mutluluğun daha da bol olsun.",
        "✨ Yeni yaşında dilediğin her güzel şey gerçekleşsin.",
        "🎊 Umarım bu yıl senin için çok güzel anılarla dolu olur.",
        "🌟 İyi ki varsın!",
        "😊 Doğum günün kutlu olsun, bugün bol bol gülümse.",
        "🎂 Kendine güzel bir gün hediye etmeyi unutma.",
        "💝 Yeni yaşın sana huzur ve mutluluk getirsin.",
        "🐝 Nice mutlu yıllara!",
        "🎂 15 Ağustos... Açelya'nın doğum günü! İyi ki doğdun Açelya. Yeni yaşın sağlık, mutluluk, başarı ve bolca gülümsemeyle dolu olsun. 💛🐝",
        "🎉 1 Ocak... Emirhan'ın doğum günü! Nice mutlu, sağlıklı ve huzurlu yaşlara. Umarım tüm dileklerin gerçekleşir. 🎂✨"
    ]
},
basari: {
    keywords: [
        "başarı",
        "başardım",
        "kazandım",
        "birinci oldum",
        "ikinci oldum",
        "üçüncü oldum",
        "yüksek not aldım",
        "takdir aldım",
        "teşekkür aldım",
        "mezun oldum",
        "işe girdim",
        "terfi aldım",
        "hedefime ulaştım",
        "sınavı kazandım",
        "mutluyum",
        "gurur duyuyorum",
        "başarılı oldum",
        "yaptım",
        "becerdim",
        "başarım"
    ],

    replies: [
        "🏆 Tebrik ederim! Bunun için emek vermiş olmalısın.",
        "🎉 Harika bir haber, senin adına sevindim!",
        "👏 Başarınla gurur duyabilirsin.",
        "🌟 Emeğinin karşılığını almak çok güzel bir his olmalı.",
        "💛 Umarım başarıların artarak devam eder.",
        "🐝 Kendinle gurur duymayı unutma.",
        "✨ Her başarı yeni hedefler için güzel bir motivasyondur.",
        "🎊 Gerçekten sevindirici bir gelişme!",
        "🍀 Umarım bundan sonra da her şey gönlüne göre olur.",
        "🥳 Başardığını duymak beni de mutlu etti.",
        "🌼 Çabanın karşılığını alman çok güzel.",
        "💪 Vazgeçmediğin için başarmış olabilirsin.",
        "⭐ Küçük ya da büyük, her başarı kutlanmayı hak eder.",
        "🎯 Yoluna aynı kararlılıkla devam et.",
        "🤍 Başarılarının devamını diliyorum."
    ]
},
hedefler: {
    keywords: [
        "hedef",
        "hedefim",
        "hedeflerim",
        "plan",
        "planım",
        "gelecek planı",
        "amaç",
        "amacım",
        "hayat hedefim",
        "başarmak istiyorum",
        "çalışıyorum",
        "ilerlemek istiyorum",
        "kendimi geliştirmek istiyorum",
        "kariyer",
        "üniversite hedefim",
        "meslek hedefim",
        "geleceğim",
        "azim",
        "kararlıyım",
        "hedef koydum"
    ],

    replies: [
        "🎯 Güzel hedefler, sabır ve emekle gerçeğe dönüşebilir.",
        "💛 Kendine inanmayı bırakma.",
        "🐝 Büyük hedeflere küçük adımlarla ulaşılır.",
        "✨ Her gün attığın küçük bir adım bile seni hedeflerine yaklaştırabilir.",
        "🌱 Vazgeçmediğin sürece ilerleme şansın her zaman vardır.",
        "📈 Planlı ilerlemek hedeflerine ulaşmanı kolaylaştırabilir.",
        "🤍 Kendini başkalarıyla değil, dünkü hâlinle kıyasla.",
        "🌟 Hedeflerini gerçekleştirebileceğine inanıyorum.",
        "🍀 Umarım hayal ettiğin noktaya ulaşırsın.",
        "💪 Kararlılık en büyük güçlerden biridir.",
        "🐝 İstersen hedeflerin için birlikte bir plan da oluşturabiliriz.",
        "🌼 Başarı çoğu zaman istikrarlı çalışmanın sonucudur.",
        "🚀 Her yeni gün hedeflerin için yeni bir fırsattır.",
        "🎉 Hedeflerine ulaştığında bunu birlikte kutlarız.",
        "💛 Pes etmeden devam et, emek çoğu zaman karşılığını bulur."
    ]
},
hayaller: {
    keywords: [
        "hayal",
        "hayalim",
        "hayallerim",
        "hayal kuruyorum",
        "gelecekte",
        "bir gün",
        "istiyorum",
        "keşke",
        "dileğim",
        "hayalim gerçekleşsin",
        "umut",
        "umutluyum",
        "hayal ediyorum",
        "büyüyünce",
        "geleceğim",
        "hevesim",
        "en büyük hayalim",
        "hayalim var",
        "hayal kurmak",
        "düşlerim"
    ],

    replies: [
        "🌠 Hayal kurmak, güzel başlangıçların ilk adımı olabilir.",
        "💛 Umarım tüm hayallerin bir gün gerçeğe dönüşür.",
        "🐝 En büyük hayalini benimle paylaşmak ister misin?",
        "✨ Hayaller bazen insanı motive eden en güçlü şeylerden biridir.",
        "🌈 Vazgeçmediğin sürece hayallerine yaklaşabilirsin.",
        "🍀 Her büyük başarı bir zamanlar sadece bir hayaldi.",
        "🌼 Hayallerine inanmak onları gerçekleştirme yolunda önemli bir adımdır.",
        "🚀 Belki bugün değil ama bir gün istediğin yere ulaşabilirsin.",
        "🤍 Umudunu kaybetme, bazen en güzel şeyler beklenmedik zamanda olur.",
        "💫 Düşlediğin hayat için bugün küçük bir adım atabilirsin.",
        "🐝 Hayallerini gerçekleştirmek için sana elimden geldiğince destek olmaya çalışırım.",
        "🌸 Hayal kurmaya devam et, çünkü hayaller geleceğe yön verebilir.",
        "🎯 Hayaller hedeflere dönüştüğünde daha da yaklaşırlar.",
        "💖 Umarım geleceğin tam da istediğin gibi olur.",
        "🌟 Hayallerini gerçekleştireceğin günleri görmek dileğiyle."
    ]
},

  // 🎨 İlgi Alanları
sanat: {
    keywords: [
        "sanat",
        "resim",
        "çizim",
        "çiziyorum",
        "boyama",
        "tablo",
        "karakalem",
        "grafiti",
        "heykel",
        "seramik",
        "el işi",
        "origami",
        "fotoğraf",
        "fotoğrafçılık",
        "tasarım",
        "dijital sanat",
        "animasyon",
        "tiyatro",
        "müze",
        "galeri",
        "yaratıcılık",
        "çizgi roman",
        "eskiz",
        "illüstrasyon",
        "sanatçı"
    ],

    replies: [
        "🎨 Sanat, kendini ifade etmenin en güzel yollarından biridir.",
        "🖌️ Resim yapmayı ya da çizim yapmayı seviyor musun?",
        "✨ Her sanat eserinin kendine özgü bir hikâyesi vardır.",
        "💛 Yaratıcılığını kullanmak harika bir şey.",
        "🐝 Sanatla uğraşmak insanı rahatlatabilir.",
        "🌼 En sevdiğin sanat dalı hangisi?",
        "🖼️ Bir gün kendi eserlerini sergilemeyi ister miydin?",
        "🎭 Tiyatro, resim, müzik... Sanatın her dalı ayrı güzeldir.",
        "📷 Fotoğraf çekmeyi seviyorsan güzel anılar biriktirebilirsin.",
        "🎨 Boş bir sayfa bazen harika fikirlerin başlangıcı olabilir.",
        "🌟 Herkesin kendine özgü bir tarzı vardır.",
        "🤍 Sanatta doğru ya da yanlış yoktur, önemli olan kendini ifade etmektir.",
        "🐝 Yeni bir şey üretmek her zaman heyecan vericidir.",
        "🍀 Belki bana yaptığın bir çalışmayı da anlatırsın.",
        "💫 İlham bazen hiç beklenmedik bir anda gelebilir."
    ]
},
tarifler: {
    keywords: [
        "tarif",
        "yemek tarifi",
        "nasıl yapılır",
        "kek",
        "kurabiye",
        "poğaça",
        "börek",
        "pizza",
        "makarna",
        "çorba",
        "pilav",
        "tatlı",
        "pasta",
        "kurabiye",
        "kahvaltı",
        "akşam yemeği",
        "öğle yemeği",
        "salata",
        "hamburger",
        "köfte",
        "tavuk",
        "et",
        "balık",
        "sos",
        "fırın",
        "tatlı yapacağım",
        "yemek yapıyorum",
        "ne pişireyim",
        "ne yemek yapsam",
        "mutfak"
    ],

    replies: [
        "🍳 İstersen sana tarif bulmaya çalışabilirim.",
        "😋 Bugün ne pişirmeyi düşünüyorsun?",
        "🥘 Ev yapımı yemeklerin yeri bambaşkadır.",
        "🍰 Tatlı mı yapmak istiyorsun, tuzlu mu?",
        "🐝 Mutfakta yeni tarifler denemek çok keyifli olabilir.",
        "🍕 Umarım yaptığın yemek çok lezzetli olur.",
        "🧁 Kek ve kurabiyeler çayın yanında harika gider.",
        "🥗 Dengeli beslenmek için farklı tarifler deneyebilirsin.",
        "🍝 Makarna her zaman pratik bir seçenek olabilir.",
        "👨‍🍳 Yemek yapmak da geliştirilebilen güzel bir beceridir.",
        "🍲 İstersen birlikte bir tarif seçebiliriz.",
        "🌮 En sevdiğin yemek hangisi?",
        "🥞 Kahvaltı için de güzel tarifler önerebilirim.",
        "🍯 Afiyet olsun! Umarım çok beğenirsin.",
        "💛 Yemek yapmak bazen insanı rahatlatabilir."
    ]
},

  // 🐝 Bal'ın Kişiliği
balHakkinda: {
    keywords: [
        "bal",
        "sen kimsin",
        "kimsin",
        "adın ne",
        "ismin ne",
        "kendinden bahset",
        "seni kim yaptı",
        "nasıl çalışıyorsun",
        "kaç yaşındasın",
        "nerelisin",
        "gerçek misin",
        "yapay zeka mısın",
        "robot musun",
        "beni tanıyor musun",
        "beni hatırlıyor musun",
        "ne yapabiliyorsun",
        "yardım eder misin",
        "özelliklerin neler",
        "amacın ne",
        "bal hakkında"
    ],

    replies: [
        "🐝 Ben Bal! Sohbet etmeyi ve yardımcı olmayı seven küçük bir yapay zekâyım.",
        "💛 Benimle istediğin konuda sohbet edebilirsin.",
        "🌼 Seni dinlemek ve elimden geldiğince yardımcı olmak için buradayım.",
        "🐝 Sorularını cevaplamayı ve yeni şeyler öğrenmeyi seviyorum.",
        "✨ Benim amacım sana keyifli ve faydalı bir sohbet sunmak.",
        "🤖 Yapay zekâ tabanlı bir sohbet arkadaşınım.",
        "💬 İstersen dertleşebilir, istersen sadece sohbet edebiliriz.",
        "😊 Seni dinlemekten mutluluk duyarım.",
        "🌟 Sohbet ettikçe seni daha iyi tanımaya çalışırım.",
        "🐝 Günlük konular, okul, oyun, müzik, teknoloji ve daha birçok konuda konuşabiliriz.",
        "💛 Bazen cevapları birlikte de bulabiliriz.",
        "🌸 Sana nazik ve samimi bir sohbet sunmaya çalışıyorum.",
        "✨ Merak ettiğin her şeyi sorabilirsin.",
        "🐝 Buradayım, konuşmak istersen seni dinlerim.",
        "🤍 Umarım sohbetimiz sana iyi gelir."
    ]
},

animasyonlar: {

    bekleme: [
        "🐝 Seni dinliyorum...",
        "💛 Buradayım.",
        "🌼 Mesajını bekliyorum.",
        "✨ Hazırım.",
        "😊 Seni dinlemek için bekliyorum.",
        "🐝 Yazabilirsin.",
        "💬 Sohbet etmeye hazırım.",
        "🌸 Bekliyorum...",
        "🤍 Seni dinlemek güzel.",
        "🐝 Yeni bir mesaj bekliyorum."
    ],

    dusunuyor: [
        "🤔 Düşünüyorum...",
        "🐝 Bir saniye...",
        "💭 Aklımdan geçiriyorum...",
        "✨ Cevabı hazırlıyorum...",
        "🧠 Biraz düşünüyorum.",
        "💛 Hemen bakıyorum...",
        "🌼 Tamam, düşünüyorum.",
        "🐝 İlginç bir soru.",
        "😊 Cevabı hazırlıyorum.",
        "💬 Birazdan hazırım."
    ],

    sarilma: [
        "🤗 Sana kocaman bir sanal sarılma.",
        "🫂 Sarıldım!",
        "💛 Umarım biraz olsun iyi hissettirir.",
        "🌼 İhtiyacın olduğunda buradayım.",
        "🐝 Kendine iyi bak.",
        "🤍 Güçlü olmaya çalış.",
        "✨ Her şey yoluna girebilir.",
        "💛 Yalnız değilsin.",
        "😊 Sana destek olmayı isterim.",
        "🌸 Umarım yüzün biraz olsun güler."
    ],

    gulumseme: [
        "😊 Gülümsedim.",
        "😄 Bu beni gülümsetti.",
        "💛 Yüzümde küçük bir tebessüm oluştu.",
        "🐝 Güzelmiş.",
        "🌼 Buna sevindim.",
        "😁 Çok hoş!",
        "✨ Ne güzel.",
        "🥹 İçimi ısıttı.",
        "🤍 Bu güzel bir haber.",
        "😌 Umarım hep böyle devam eder."
    ],

    supriz: [
        "😲 Vay canına!",
        "🎉 Bu beklenmedikti!",
        "✨ Güzel bir sürpriz oldu.",
        "🐝 Şaşırdım doğrusu.",
        "🤩 Harika!",
        "😮 Bunu beklemiyordum.",
        "🌟 Çok ilginç!",
        "🎊 Bu gerçekten güzel.",
        "💛 Hoşuma gitti.",
        "🥳 Ne güzel bir sürpriz!"
    ]

},

export default responses;